AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Lambda function for trading automation

Resources:
  TradingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src/lambda/trading
      Handler: tradovate_token.lambda_handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 128
      Tracing: Active
      Events:
        WebhookAPI:
          Type: Api
          Properties:
            Path: /webhook
            Method: POST
      LoggingConfig:
        LogFormat: JSON
        LogGroup: "/aws/lambda/trading-function"
        RetentionInDays: 30
      Policies:
      - AWSXrayWriteOnlyAccess
