name: Deploy Lambda

on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambda/**'  # Only trigger on Lambda code changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        cd src/lambda
        pip install -r requirements.txt -t .

    - name: Create deployment package
      run: |
        cd src/lambda
        zip -r ../../terraform/lambda_function.zip ./*

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Update Lambda function
      run: |
        aws lambda update-function-code \
          --function-name trading-prod-function \
          --zip-file fileb://terraform/lambda_function.zip