name: Deploy Lambdas

on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambda/**'
      - 'src/lambda2/**'
      - 'src/lambda3/**'
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.7.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-duration-seconds: 1200
        role-skip-session-tagging: true
        mask-aws-account-id: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and package Lambda 1
      run: |
        cd src/lambda
        docker buildx build --platform linux/amd64 --load -t lambda-build .
        docker create --name lambda-container lambda-build
        docker cp lambda-container:/lambda_function.zip ../../terraform/
        docker rm lambda-container
        aws s3 cp ../../terraform/lambda_function.zip s3://trading-lambda-deployment/lambda_function.zip

    - name: Build and push Lambda 2 container
      run: |
        cd src/lambda2
        IMAGE_TAG="trading-prod-symbol-lookup:latest"
        REGISTRY_URL="${{ steps.login-ecr.outputs.registry }}"
        FULL_IMAGE_TAG="$REGISTRY_URL/$IMAGE_TAG"
        
        docker buildx build --platform linux/amd64 --load -t $FULL_IMAGE_TAG .
        docker push $FULL_IMAGE_TAG

    - name: Build and package Lambda 3
      run: |
        cd src/lambda3
        docker buildx build --platform linux/amd64 --load -t lambda3-build .
        docker create --name lambda3-container lambda3-build
        docker cp lambda3-container:/lambda3_function.zip ../../terraform/
        docker rm lambda3-container
        aws s3 cp ../../terraform/lambda3_function.zip s3://trading-lambda-deployment/lambda3_function.zip

    - name: Setup Terraform Plugin Cache
      run: |
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          .terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Check for Configuration Drift
      working-directory: ./terraform
      run: |
        terraform init
        terraform validate
        terraform refresh
        terraform plan -detailed-exitcode -lock=false | tee plan_output.txt
        PLAN_EXIT_CODE=$?

        if [ $PLAN_EXIT_CODE -eq 2 ]; then
          if grep -q "~ code_sha256" plan_output.txt && \
              grep -q "~ last_modified" plan_output.txt && \
              grep -q "~ source_code_size" plan_output.txt && \
              ! grep -qE "~ (?!code_sha256|last_modified|source_code_size)" plan_output.txt; then
            echo "Only expected Lambda-related changes detected, continuing..."
            exit 0
          else
            echo "❌ Configuration drift detected! Please fix before deploying."
            cat plan_output.txt
            exit 1
          fi
        elif [ $PLAN_EXIT_CODE -eq 0 ]; then
          echo "No changes detected"
          exit 0
        else
          echo "Error running terraform plan"
          exit 1
        fi

    - name: Update Lambda functions
      run: |
        aws lambda update-function-code \
          --function-name trading-prod-function \
          --s3-bucket trading-lambda-deployment \
          --s3-key lambda_function.zip

        aws lambda update-function-code \
          --function-name trading-prod-symbol-lookup \
          --image-uri ${{ steps.login-ecr.outputs.registry }}/trading-prod-symbol-lookup:latest
        
        aws lambda update-function-code \
          --function-name trading-prod-coinbase \
          --s3-bucket trading-lambda-deployment \
          --s3-key lambda3_function.zip