name: Deploy Lambdas

on:
  push:
    branches: [ main ]
    paths:
      - 'src/lambda/**'
      - 'src/lambda2/**'
      - 'src/lambda3/**'
      - 'terraform/**'
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  issues: write

jobs:
  build-and-check:
    runs-on: ubuntu-latest
    env:
      ACTIONS_STEP_DEBUG: false
    
    steps:
    - uses: actions/checkout@v4

    - name: Configure secret masking
      run: |
        echo "::add-mask::${{ secrets.OANDA_SECRET }}"
        echo "::add-mask::${{ secrets.OANDA_ACCOUNT }}"
        echo "::add-mask::${{ secrets.DATABENTO_API_KEY }}"
        echo "::add-mask::${{ secrets.TRADOVATE_USERNAME }}"
        echo "::add-mask::${{ secrets.TRADOVATE_PASSWORD }}"
        echo "::add-mask::${{ secrets.TRADOVATE_DEVICE_ID }}"
        echo "::add-mask::${{ secrets.TRADOVATE_CID }}"
        echo "::add-mask::${{ secrets.TRADOVATE_SECRET }}"
        # Add pattern matching for dynamic values
        echo "::add-mask::organizations/d0a73c0b-1c05-4ad5-94b9-232dcf7e80f4"
        echo "::add-mask::trading-prod-symbol-lookup"
        echo "::add-mask::trading-prod-function"
        echo "::add-mask::trading-prod-coinbase"

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.12'

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: '1.10.2'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
        role-duration-seconds: 1200
        role-skip-session-tagging: true
        mask-aws-account-id: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and package Lambda 1
      run: |
        cd src/lambda
        docker buildx build --platform linux/amd64 --load -t lambda-build .
        docker create --name lambda-container lambda-build
        docker cp lambda-container:/tmp/lambda/lambda_function.zip ../../terraform/
        docker rm lambda-container
        aws s3 cp ../../terraform/lambda_function.zip s3://trading-lambda-deployment/lambda_function.zip \
          --sse aws:kms \
          --sse-kms-key-id "${KMS_KEY_ARN}"
      env:
        KMS_KEY_ARN: ${{ secrets.KMS_KEY_ARN }}

    - name: Build and push Lambda 2 container
      id: build-lambda2
      run: |
        cd src/lambda2
        COMMIT_SHORT_SHA=$(git rev-parse --short HEAD)
        REPOSITORY_NAME="trading-prod-symbol-lookup"
        REGISTRY_URL="${{ steps.login-ecr.outputs.registry }}"
        
        FULL_IMAGE_TAG="${REGISTRY_URL}/${REPOSITORY_NAME}:${COMMIT_SHORT_SHA}"
        
        # Build the image
        docker buildx build --platform linux/amd64 --load -t $FULL_IMAGE_TAG .
        
        # Push the image to ECR
        docker push $FULL_IMAGE_TAG
        
        # Save the image URI for later use
        echo "image_uri=${FULL_IMAGE_TAG}" >> $GITHUB_OUTPUT
    
        # Verify the push
        aws ecr describe-images --repository-name ${REPOSITORY_NAME} --image-ids imageTag=${COMMIT_SHORT_SHA}

    - name: Build and package Lambda 3
      run: |
        cd src/lambda3
        docker buildx build --platform linux/amd64 --load -t lambda3-build .
        docker create --name lambda3-container lambda3-build
        docker cp lambda3-container:/tmp/lambda/lambda3_function.zip ../../terraform/
        docker rm lambda3-container
        aws s3 cp ../../terraform/lambda3_function.zip s3://trading-lambda-deployment/lambda3_function.zip \
          --sse aws:kms \
          --sse-kms-key-id "${KMS_KEY_ARN}"
      env:
        KMS_KEY_ARN: ${{ secrets.KMS_KEY_ARN }}

    - name: Setup Terraform Plugin Cache
      run: |
        mkdir -p ~/.terraform.d/plugin-cache
        echo 'plugin_cache_dir = "$HOME/.terraform.d/plugin-cache"' > ~/.terraformrc

    - name: Cache Terraform
      uses: actions/cache@v4
      with:
        path: |
          ~/.terraform.d/plugin-cache
          .terraform
        key: ${{ runner.os }}-terraform-${{ hashFiles('**/.terraform.lock.hcl') }}
        restore-keys: |
          ${{ runner.os }}-terraform-

    - name: Check for Configuration Drift
      working-directory: ./terraform
      run: |
        terraform init
        terraform validate
        terraform refresh
        terraform plan -detailed-exitcode -lock=false | tee plan_output.txt
        PLAN_EXIT_CODE=$?

        # Filter sensitive data from plan output before storing
        sed -i 's/\(".*secret.*": "\)[^"]*\("/\1******\2/g' plan_output.txt

        if [ $PLAN_EXIT_CODE -eq 2 ]; then
          if grep -q "~ code_sha256" plan_output.txt && \
              grep -q "~ last_modified" plan_output.txt && \
              grep -q "~ source_code_size" plan_output.txt && \
              ! grep -qE "~ (?!code_sha256|last_modified|source_code_size)" plan_output.txt; then
            echo "Only expected Lambda-related changes detected, continuing..."
            exit 0
          else
            echo "❌ Configuration drift detected! Please fix before deploying."
            cat plan_output.txt
            exit 1
          fi
        elif [ $PLAN_EXIT_CODE -eq 0 ]; then
          echo "No changes detected"
          exit 0
        else
          echo "Error running terraform plan"
          exit 1
        fi

    - name: Update Lambda functions
      run: |
        aws lambda update-function-code \
          --function-name trading-prod-function \
          --s3-bucket trading-lambda-deployment \
          --s3-key lambda_function.zip
    
        # Use the saved image URI from the build step
        aws lambda update-function-code \
          --function-name trading-prod-symbol-lookup \
          --image-uri "${{ steps.build-lambda2.outputs.image_uri }}"
        
        aws lambda update-function-code \
          --function-name trading-prod-coinbase \
          --s3-bucket trading-lambda-deployment \
          --s3-key lambda3_function.zip